unique_ids:
  assets:
    standard-page.html: VB5R4JBTMHZFNN6D5LTMYR7M7LUOBPOV
    theme.css: ZEZ7RXJV6ISP3S4H2TGPZFHN4HCZ2Y2Q
  forms:
    Form1: WPNH5LONCCRYYDEDDLN7YUNADDUXUL67
  modules: {}
  scripts: {}
  server_modules: {}
